(()=>{
const $$=(s,r=document)=>[...r.querySelectorAll(s)],$=(s,r=document)=>r.querySelector(s);
const page=document.body.dataset.page;
$$('.chapter-strip a').forEach(a=>{const href=a.getAttribute('href')||'';if(((page==='projects'||page==='project')&&href==='projects.html')||(page==='process'&&href==='process.html')||(page==='estimate'&&href==='estimate.html'))a.setAttribute('aria-current','page')});
// material board
const materialData={stone:{image:'assets/stone-detail.svg',alt:'Fieldstone material study',code:'FIELDSTONE / 01',title:'Steps, retaining edges, sitting walls.',body:'Used where mass and permanence should read as part of the ground.'},gravel:{image:'assets/terrace-daylight.svg',alt:'Gravel and terrace material study',code:'GRAVEL / 02',title:'Permeable courts, paths, threshold zones.',body:'A quieter surface where drainage and a softer edge matter more than a hard slab.'},steel:{image:'assets/plan-fragment.svg',alt:'Plan showing restrained edging and site geometry',code:'STEEL / 03',title:'Thin edges, grade changes, discreet structure.',body:'Used sparingly where a narrow line needs to hold soil without becoming the visual subject.'},planting:{image:'assets/planting-close.svg',alt:'Layered planting texture',code:'PLANTING / 04',title:'Structure first, seasonal change second.',body:'Trees and durable ground layers establish the long shape; flowers and fine texture move through it.'}};
$$('[data-material]').forEach(btn=>btn.addEventListener('click',()=>{const d=materialData[btn.dataset.material],img=$('[data-material-image]'),note=$('[data-material-note]');$$('[data-material]').forEach(b=>{b.classList.toggle('active',b===btn);b.setAttribute('aria-pressed',b===btn?'true':'false')});if(img){img.src=d.image;img.alt=d.alt}if(note)note.innerHTML=`<span>${d.code}</span><strong>${d.title}</strong><p>${d.body}</p>`}));
// comparisons
$$('[data-comparison]').forEach(box=>{const range=$('[data-compare-range]',box),after=$('[data-after]',box),line=$('[data-line]',box);const sync=()=>{const v=Number(range.value);after.style.clipPath=`inset(0 ${100-v}% 0 0)`;line.style.left=v+'%'};range.addEventListener('input',sync);sync()});
// project filters
const filterButtons=$$('[data-filter]'),cards=$$('[data-tags]');if(filterButtons.length){const params=new URLSearchParams(location.search),wanted=params.get('filter')||'all';const valid=filterButtons.some(b=>b.dataset.filter===wanted)?wanted:'all';const apply=(value)=>{let shown=0;filterButtons.forEach(b=>{const on=b.dataset.filter===value;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on?'true':'false')});cards.forEach(c=>{const on=value==='all'||(c.dataset.tags||'').split(/\s+/).includes(value);c.hidden=!on;if(on)shown++});const empty=$('[data-empty]');if(empty)empty.hidden=shown>0;const url=new URL(location.href);if(value==='all')url.searchParams.delete('filter');else url.searchParams.set('filter',value);history.replaceState(null,'',url)};filterButtons.forEach(b=>b.addEventListener('click',()=>apply(b.dataset.filter)));apply(valid)}
// project detail data
const projects={
'birch-court':{index:'Case 01 / Garden + stone',title:'Birch Court',summary:'A quiet stone room set into a narrow rear garden.',hero:'assets/project-birch.svg',alt:'Birch Court finished landscape',site:'Narrow residential rear yard',ground:'Clay over compacted fill',scope:'Drainage, stone, planting, lighting',season:'Built spring · planted autumn',problem:'The yard moved water toward the house and had no useful level place to sit.',story:'The project began with drainage and grade. A narrow permeable walk moved circulation to the side, leaving enough width for one simple court. Stone walls hold the new elevations while the planting softens the geometry over time.',materials:['Split fieldstone retaining edges','Permeable gravel sub-base','Large-format thermal bluestone','Birch, sedge, fern and hydrangea'],next:'rain-garden'},
'rain-garden':{index:'Case 02 / Planting + water',title:'North Slope',summary:'A wet edge turned into the part of the garden that carries the season.',hero:'assets/project-rain.svg',alt:'North Slope rain garden',site:'Sloped side and rear yard',ground:'Compacted loam / seasonal runoff',scope:'Drainage, crossing, planting',season:'Built autumn · established spring',problem:'Stormwater crossed the main walk and collected at the lowest corner.',story:'Rather than force the water into a hidden pipe, the grade was opened into a shallow planted basin. A simple stone crossing keeps the route dry while sedges, iris and shrubs take the seasonal wetting.',materials:['River-washed stone crossing','Open-graded gravel base','Sedge and iris matrix','Multi-stem serviceberry'],next:'entry-walk'},
'entry-walk':{index:'Case 03 / Stone + planting',title:'Stone Entry',summary:'A front approach made quieter by giving stone and planting equal weight.',hero:'assets/project-entry.svg',alt:'Stone Entry landscape',site:'Street-facing front slope',ground:'Thin urban soil over rubble',scope:'Steps, wall, walk, screening',season:'Built summer',problem:'The approach felt steep and exposed, with failing concrete steps and no planted threshold.',story:'The new walk shifts gently across the slope before meeting a short stone stair. Planting occupies the remaining grade as one continuous mass, so the masonry reads as a line through the garden rather than a separate object.',materials:['Dry-laid fieldstone step faces','Thermal bluestone treads','Amended planting soil','Grasses, inkberry and oakleaf hydrangea'],next:'hill-terrace'},
'hill-terrace':{index:'Case 04 / Stone + garden',title:'Hill Terrace',summary:'Three small grade changes turned into one usable outdoor room.',hero:'assets/terrace-daylight.svg',alt:'Hill Terrace outdoor room',site:'Steep rear garden',ground:'Sandy loam / existing mature trees',scope:'Terraces, wall, planting, lighting',season:'Built spring–summer',problem:'The only flat area sat against the house while the rest of the yard dropped away too quickly to use.',story:'A sequence of low walls divides the slope into three modest elevations. The middle level becomes the dining terrace; upper and lower levels stay planted, keeping the whole intervention tied to the garden.',materials:['Thermal bluestone paving','Split stone low walls','Steel stair edge','Grasses, ferns and flowering shrubs'],next:'shade-border'},
'shade-border':{index:'Case 05 / Planting',title:'Shade Border',summary:'A deep-shade edge rebuilt around foliage, structure and a restrained path.',hero:'assets/planting-close.svg',alt:'Shade Border planting composition',site:'Mature-tree side garden',ground:'Dry shade / root competition',scope:'Planting edit, path, soil repair',season:'Planted autumn',problem:'Thin lawn under mature trees left the side yard bare for most of the year.',story:'The lawn was removed and replaced with a layered shade planting that can tolerate roots and dry summer soil. A narrow gravel path keeps the route legible without dividing the planting into beds.',materials:['Fine gravel path','Compost and leaf-mold topdress','Sedge, fern and epimedium','Multi-stem witch hazel'],next:'dining-court'},
'dining-court':{index:'Case 06 / Stone',title:'Dining Court',summary:'A hard-working terrace made from one stone and one edge condition.',hero:'assets/stone-detail.svg',alt:'Dining Court fieldstone detail',site:'Rear kitchen threshold',ground:'Mixed fill / poor drainage',scope:'Paving, seat wall, drainage',season:'Built summer',problem:'A cracked patio trapped water at the kitchen door and broke the yard into awkward leftover strips.',story:'The new court pitches water to a concealed gravel edge and uses a single paving module throughout. A low fieldstone wall creates the outer boundary and doubles as informal seating.',materials:['Large-format bluestone','Split fieldstone seat wall','Linear gravel drain','Simple herb and grass edge'],next:'birch-court'}};
if(page==='project'){const id=new URLSearchParams(location.search).get('id')||'birch-court',d=projects[id]||projects['birch-court'];const set=(sel,val)=>{const el=$(sel);if(el)el.textContent=val};set('[data-project-index]',d.index);set('[data-project-title]',d.title);set('[data-project-summary]',d.summary);set('[data-project-site]',d.site);set('[data-project-ground]',d.ground);set('[data-project-scope]',d.scope);set('[data-project-season]',d.season);set('[data-project-problem]',d.problem);set('[data-project-story]',d.story);const hero=$('[data-project-hero]');if(hero){hero.src=d.hero;hero.alt=d.alt}const ul=$('[data-project-materials]');if(ul)ul.innerHTML=d.materials.map(x=>`<li>${x}</li>`).join('');const next=$('[data-next-project]');if(next)next.href='project.html?id='+d.next;document.title=d.title+' — Fieldstone Landscape'}
// process step tabs
const stepData={observe:{tag:'01 / Observe',title:'Start with what cannot be argued with.',body:'Light, grade, runoff, access, existing trees, utilities, views and the daily path through the site are recorded before a new line is drawn.'},organize:{tag:'02 / Organize',title:'Give use and movement a clear order.',body:'Outdoor rooms, thresholds, routes and important views are arranged before a material palette is selected.'},build:{tag:'03 / Build',title:'Resolve water and structure before finish.',body:'Excavation, drainage, retaining work, utilities and sub-bases establish the hidden geometry that lets the visible work age well.'},plant:{tag:'04 / Plant',title:'Plant into the structure, then let it change.',body:'Trees and long-lived ground layers establish the frame. Finer seasonal planting edits the frame without fighting it.'}};
$$('[data-step]').forEach(btn=>btn.addEventListener('click',()=>{const key=btn.dataset.step,d=stepData[key],copy=$('[data-step-copy]');$$('[data-step]').forEach(b=>{const on=b===btn;b.classList.toggle('active',on);b.setAttribute('aria-selected',on?'true':'false')});$$('[data-plan-layer]').forEach(layer=>layer.hidden=layer.dataset.planLayer!=='base'&&layer.dataset.planLayer!==key);if(copy)copy.innerHTML=`<span>${d.tag}</span><h2>${d.title}</h2><p>${d.body}</p>`}));
// estimate planner
const form=$('[data-project-form]');if(form){const size=$('[data-site-size]'),sizeOut=$('[data-site-size-output]'),priority=$('[data-priority]'),timing=$('[data-timing]');const scaleFor=n=>n<1250?'Compact':n<2500?'Focused':n<4500?'Broad':'Whole-site';const sync=()=>{const type=$('input[name="project_type"]:checked',form)?.value||'Garden renovation',n=Number(size.value);sizeOut.textContent=n.toLocaleString()+' sq ft';$('[data-summary-title]').textContent=type;$('[data-summary-size]').textContent=n.toLocaleString()+' sq ft';$('[data-summary-priority]').textContent=priority.value;$('[data-summary-timing]').textContent=timing.value;$('[data-summary-scale]').textContent=scaleFor(n)};form.addEventListener('input',sync);form.addEventListener('change',sync);sync();const briefText=()=>{const fd=new FormData(form),n=Number(size.value);return `FIELDSTONE PROJECT BRIEF\nProject: ${fd.get('project_type')}\nSite area: ${n.toLocaleString()} sq ft\nPriority: ${fd.get('priority')}\nTiming: ${fd.get('timing')}\nPlanning scale: ${scaleFor(n)}\nArea: ${fd.get('area')||'Not specified'}\nNotes: ${fd.get('notes')||'Not yet entered'}\nName: ${fd.get('name')||'Not yet entered'}\nEmail: ${fd.get('email')||'Not yet entered'}`};$('[data-copy-brief]')?.addEventListener('click',async()=>{const status=$('[data-copy-status]');try{await navigator.clipboard.writeText(briefText());status.textContent='Brief copied.'}catch(_){status.textContent='Copy is unavailable in this browser.'}});form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const record={savedAt:new Date().toISOString(),brief:briefText()};try{localStorage.setItem('fieldstone:last-project-brief',JSON.stringify(record))}catch(_){}const status=$('[data-form-status]');status.textContent='Saved in this browser. No message or email was sent.';status.hidden=false;status.focus()})}
})();