(() => {
  const header=document.querySelector('.site-header');
  const setHeader=()=>header&&header.classList.toggle('is-scrolled',scrollY>12); setHeader(); addEventListener('scroll',setHeader,{passive:true});
  const btn=document.querySelector('[data-menu-button]'), nav=document.querySelector('[data-mobile-nav]');
  const close=()=>{if(!nav||!btn)return;nav.classList.remove('open');btn.setAttribute('aria-expanded','false')};
  if(btn&&nav)btn.addEventListener('click',()=>{const open=nav.classList.toggle('open');btn.setAttribute('aria-expanded',String(open))});
  if(nav)nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',close)); addEventListener('keydown',e=>e.key==='Escape'&&close());
  document.querySelectorAll('[data-accordion]').forEach(item=>{const q=item.querySelector('button');if(!q)return;q.setAttribute('aria-expanded',item.classList.contains('open')?'true':'false');q.addEventListener('click',()=>{const open=item.classList.toggle('open');q.setAttribute('aria-expanded',String(open))})});
  document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{const group=button.closest('[data-filter-group]');if(!group)return;group.querySelectorAll('[data-filter]').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false')});button.classList.add('active');button.setAttribute('aria-pressed','true');const value=button.dataset.filter;document.querySelectorAll('[data-filter-item]').forEach(item=>item.hidden=value!=='all'&&item.dataset.filterItem!==value)}));
  document.querySelectorAll('form[data-interactive-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const status=form.querySelector('[data-form-status]');if(status){status.textContent=form.dataset.success||'Thanks — your request has been recorded.';status.hidden=false;status.tabIndex=-1;status.focus()}try{const entries=Object.fromEntries(new FormData(form).entries());localStorage.setItem('mosaic-form:'+location.pathname+':'+Date.now(),JSON.stringify({submittedAt:new Date().toISOString(),fields:entries}))}catch(_){}form.classList.add('is-complete')}));
  const slider=document.querySelector('[data-budget-slider]'); if(slider){const out=document.querySelector('[data-budget-output]');const sync=()=>{if(out)out.textContent='$'+Number(slider.value).toLocaleString()};slider.addEventListener('input',sync);sync()}

  const css=document.createElement('link');css.rel='stylesheet';css.href='consent.css';document.head.append(css);
  const key='aurora-consent-v1';
  const footer=document.querySelector('.footer-links');
  const makeLink=(label,href)=>{const a=document.createElement('a');a.textContent=label;a.href=href;return a};
  let reopen;
  if(footer){footer.append(makeLink('Privacy','privacy.html'));const b=document.createElement('button');b.type='button';b.className='privacy-link';b.textContent='Cookie settings';b.addEventListener('click',()=>reopen&&reopen());footer.append(b)}
  const save=value=>{try{localStorage.setItem(key,value)}catch(_){}document.documentElement.dataset.analytics=value==='analytics'?'on':'off';document.querySelector('[data-aurora-consent]')?.remove()};
  const show=()=>{document.querySelector('[data-aurora-consent]')?.remove();const el=document.createElement('aside');el.className='aurora-consent';el.dataset.auroraConsent='';el.setAttribute('aria-label','Privacy choices');el.innerHTML='<div class="consent-status"><i></i><span>PRIVACY CONTROL</span></div><h2>Keep the signal useful.</h2><p>Essential storage keeps the site working. Optional analytics help us understand product interest.</p><div class="consent-actions"><button data-choice="essential">Essential only</button><button class="allow" data-choice="analytics">Allow analytics</button></div><button class="consent-more" type="button">Preferences +</button><div class="consent-detail" hidden><label><input type="checkbox" checked> Anonymous product analytics</label><small>No advertising profiles or cross-site tracking.</small><button class="save" type="button">Save preferences</button></div>';document.body.append(el);el.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>save(b.dataset.choice)));const more=el.querySelector('.consent-more'),detail=el.querySelector('.consent-detail');more.addEventListener('click',()=>{detail.hidden=!detail.hidden;more.textContent=detail.hidden?'Preferences +':'Preferences −'});el.querySelector('.save').addEventListener('click',()=>save(el.querySelector('input').checked?'analytics':'essential'))};
  reopen=show; let choice=null;try{choice=localStorage.getItem(key)}catch(_){} if(choice)document.documentElement.dataset.analytics=choice==='analytics'?'on':'off';else setTimeout(show,450);
})();
