(()=>{
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const current=location.pathname.split('/').pop()||'index.html';
$$('[data-nav]').forEach(a=>{if(a.getAttribute('href')===current)a.classList.add('active')});
const menuBtn=$('[data-mobile-menu]'), mobileTabs=$('[data-mobile-tabs]');
if(menuBtn&&mobileTabs){const close=()=>{mobileTabs.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')};menuBtn.addEventListener('click',()=>{const open=!mobileTabs.classList.contains('open');mobileTabs.classList.toggle('open',open);menuBtn.setAttribute('aria-expanded',String(open))});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});$$('a',mobileTabs).forEach(a=>a.addEventListener('click',close));}
const monthData={
 'May':{status:'CLOSED 06.06',margin:'39.6%',marginDelta:'+0.4 pts',cash:'$154,820',cashDelta:'11.2 wks',ar:'$51,480',arDelta:'12.8%',flag:'3 questions',stamp:'CLOSED',questions:[['A/R','Two invoices over 45 days account for 71% of overdue receivables.'],['MARGIN','Freight expense rose faster than revenue in the west region.'],['CASH','Planned equipment deposit lands before the next major collection cycle.']]},
 'Jun':{status:'CLOSED 07.07',margin:'40.7%',marginDelta:'+1.1 pts',cash:'$169,230',cashDelta:'12.1 wks',ar:'$43,760',arDelta:'10.4%',flag:'2 questions',stamp:'CLOSED',questions:[['MARGIN','Product mix improved after a lower-margin contract ended.'],['PAYROLL','Overtime was concentrated in the final eight days of the month.']]},
 'Jul':{status:'CLOSED 08.05',margin:'41.8%',marginDelta:'+1.1 pts',cash:'$186,940',cashDelta:'13.1 wks',ar:'$38,220',arDelta:'8.9%',flag:'4 questions',stamp:'REVIEWED',questions:[['A/R','One customer balance crossed 30 days; collection timing should be confirmed before the next cash plan.'],['MARGIN','Direct labor improved 1.6 points while outside contractor spend increased.'],['TAX','Quarterly estimate reserve is below the internal target after owner distributions.'],['HIRING','Current payroll run-rate leaves room for one planned hire without reducing the 10-week cash floor.']]},
 'Aug':{status:'IN REVIEW',margin:'42.1%',marginDelta:'+0.3 pts',cash:'$178,610',cashDelta:'12.6 wks',ar:'$46,080',arDelta:'10.7%',flag:'2 questions',stamp:'OPEN',questions:[['A/R','Collections moved later than the prior two months; no concentration issue is evident yet.'],['CASH','Annual insurance renewal is included in next month’s cash schedule.']]}
};
$$('[data-month]').forEach(btn=>btn.addEventListener('click',()=>{const m=btn.dataset.month,d=monthData[m];$$('[data-month]').forEach(b=>b.setAttribute('aria-pressed',String(b===btn)));Object.entries(d).forEach(([k,v])=>{if(k==='questions')return;const el=$(`[data-field="${k}"]`);if(el)el.textContent=v});const q=$('[data-question-list]');if(q){q.innerHTML=d.questions.map((x,i)=>`<div class="question-body"><span class="flag">${String(i+1).padStart(2,'0')}</span><p><strong>${x[0]}</strong> — ${x[1]}<small>Management note · ${m} close</small></p></div>`).join('')};const toggle=$('[data-question-toggle]');if(toggle)toggle.textContent=`Hide ${d.questions.length} flags`; }));
const qToggle=$('[data-question-toggle]'),qList=$('[data-question-list]');if(qToggle&&qList){qToggle.addEventListener('click',()=>{const hidden=qList.hidden;qList.hidden=!hidden;qToggle.textContent=hidden?`Hide ${qList.children.length} flags`:`Show ${qList.children.length} flags`;qToggle.setAttribute('aria-expanded',String(hidden))})}
$$('[data-row-note]').forEach(btn=>btn.addEventListener('click',()=>{const table=btn.closest('table');$$('tr',table).forEach(r=>r.classList.remove('is-focused'));btn.closest('tr').classList.add('is-focused');const note=$('[data-focus-note]');if(note){note.querySelector('p').textContent=btn.dataset.rowNote;note.scrollIntoView({block:'nearest'})}}));
$$('[data-period]').forEach(btn=>btn.addEventListener('click',()=>{const period=btn.dataset.period;$$('[data-period]').forEach(b=>b.setAttribute('aria-pressed',String(b===btn)));$$('[data-tax-period]').forEach(row=>row.hidden=!(period==='all'||row.dataset.taxPeriod===period));}));
const calc=()=>{const cash=parseFloat($('#cash-on-hand')?.value||0), inflow=parseFloat($('#monthly-inflow')?.value||0), outflow=parseFloat($('#monthly-outflow')?.value||0), reserve=parseFloat($('#reserved-cash')?.value||0);const usable=Math.max(0,cash-reserve),burn=Math.max(0,outflow-inflow),weeks=burn>0?(usable/burn*4.33):99;const el=$('[data-runway]');if(el)el.textContent=weeks>=99?'99+':weeks.toFixed(1);const msg=$('[data-runway-note]');if(msg)msg.textContent=burn<=0?'Current inflows cover the entered monthly outflows; runway is not constrained by burn in this worksheet.':`Based on the values entered, usable cash covers approximately ${weeks.toFixed(1)} weeks of the current net burn.`;};$$('[data-calc]').forEach(i=>i.addEventListener('input',calc));calc();
const industryData={
 services:{title:'Professional services',rows:[['Client billings','$412,000','100%'],['Direct project labor','$168,400','40.9%'],['Contractor spend','$39,700','9.6%'],['Gross profit','$203,900','49.5%'],['A/R over 30 days','$31,600','7.7%']],notes:'The useful questions are project margin, utilization, contractor mix, collection timing, and owner compensation. The statement should connect labor to the work that produced the revenue.',tags:['Project margin','Utilization','Collections','WIP']},
 construction:{title:'Construction + trades',rows:[['Recognized revenue','$566,800','100%'],['Direct job costs','$351,200','62.0%'],['Gross profit','$215,600','38.0%'],['Customer deposits','$94,500','16.7%'],['Retainage receivable','$42,700','7.5%']],notes:'The accounting has to preserve job economics. Deposits, retainage, subcontractors, equipment, and work in progress all affect how much apparent profit is actually available.',tags:['Job margin','Backlog','WIP','Retainage']},
 ecommerce:{title:'E-commerce',rows:[['Net sales','$728,300','100%'],['Landed product cost','$301,900','41.5%'],['Fulfillment + freight','$88,600','12.2%'],['Contribution margin','$236,100','32.4%'],['Inventory on hand','$419,800','57.6%']],notes:'Channel revenue alone is not enough. Processor settlements, returns, inventory timing, landed cost, fulfillment, and advertising need to reconcile into one margin view.',tags:['COGS','Inventory','Contribution','Channels']},
 agency:{title:'Agencies + studios',rows:[['Retainer revenue','$286,000','71%'],['Project revenue','$118,000','29%'],['Payroll + freelance','$201,300','49.8%'],['Gross profit','$202,700','50.2%'],['Deferred revenue','$64,000','15.8%']],notes:'The operating view separates recurring retainers from project work and keeps capacity, freelance mix, project labor, and deferred revenue visible month to month.',tags:['Gross margin','Capacity','MRR','Deferred rev.']}
};
$$('[data-industry]').forEach(btn=>btn.addEventListener('click',()=>{const d=industryData[btn.dataset.industry];$$('[data-industry]').forEach(b=>b.setAttribute('aria-pressed',String(b===btn)));$('[data-industry-title]').textContent=d.title;$('[data-industry-rows]').innerHTML=d.rows.map(r=>`<div class="example-row"><span>${r[0]}</span><b>${r[1]}</b><em>${r[2]}</em></div>`).join('');$('[data-industry-notes]').textContent=d.notes;$('[data-industry-tags]').innerHTML=d.tags.map(t=>`<span>${t}</span>`).join('')}));
const form=$('[data-intake]');if(form){form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form).entries());try{localStorage.setItem('bennett-rowe-intake',JSON.stringify({savedAt:new Date().toISOString(),...data}))}catch(_){}const status=$('[data-form-status]',form);status.hidden=false;status.textContent='Your intake is saved in this browser for this local site. No message has been sent.';status.focus();form.reset()})}
})();