(()=>{
const body=document.body, menu=document.querySelector('[data-menu]'), btn=document.querySelector('[data-menu-toggle]');
let prior=null;
function setMenu(open){if(!menu||!btn)return;menu.classList.toggle('open',open);menu.setAttribute('aria-hidden',String(!open));btn.setAttribute('aria-expanded',String(open));body.classList.toggle('menu-open',open);btn.textContent=open?'MENU −':'MENU +';if(open){prior=document.activeElement;setTimeout(()=>menu.querySelector('a')?.focus(),30)}else if(prior&&prior.focus){prior.focus()}}
btn?.addEventListener('click',()=>setMenu(!menu.classList.contains('open')));document.querySelectorAll('[data-menu-close]').forEach(x=>x.addEventListener('click',()=>setMenu(false)));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu?.classList.contains('open'))setMenu(false)});
if(menu){menu.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const els=[...menu.querySelectorAll('a,button')].filter(x=>!x.disabled);if(!els.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}})}
const cursor=document.querySelector('[data-cursor-label]');document.querySelectorAll('[data-cursor]').forEach(el=>{el.addEventListener('pointerenter',()=>cursor?.classList.add('show'));el.addEventListener('pointerleave',()=>cursor?.classList.remove('show'));el.addEventListener('pointermove',e=>{if(cursor){cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'}})});
const frames=[...document.querySelectorAll('[data-frame]')];if('IntersectionObserver'in window&&frames.length&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const obs=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle('in-view',e.isIntersecting)),{threshold:.35});frames.forEach(f=>obs.observe(f))}
const looks={
 '01':{title:'Long jacket',img:'assets/look-01.svg',desc:'A narrow shoulder and continuous front line cut in dense wool barathea.',material:'Wool barathea',colour:'Black',construction:'Half canvas / hand-finished hem',origin:'Cloth woven in Biella / cut in Paris',edition:'07 / 01',next:'02',prev:'04'},
 '02':{title:'Column dress',img:'assets/look-02.svg',desc:'Washed silk suspended from a compact shoulder with a low, controlled sweep.',material:'Washed silk',colour:'Black',construction:'Bias body / internal silk facing',origin:'Silk woven in Como / cut in Paris',edition:'07 / 02',next:'03',prev:'01'},
 '03':{title:'Soft trouser',img:'assets/look-03.svg',desc:'A high, easy trouser with volume held close by a deep internal pleat.',material:'Wool twill',colour:'Ink',construction:'Single deep pleat / extended waistband',origin:'Wool woven in Prato / cut in Paris',edition:'07 / 03',next:'04',prev:'02'},
 '04':{title:'Evening coat',img:'assets/look-04.svg',desc:'A long double-wool coat reduced to shoulder, lapel and a single uninterrupted fall.',material:'Double wool',colour:'Noir',construction:'Floating canvas / horn closure',origin:'Wool woven in France / cut in Paris',edition:'07 / 04',next:'01',prev:'03'}
};
const detail=document.querySelector('[data-look-detail]');if(detail){const key=new URLSearchParams(location.search).get('look')||'01',d=looks[key]||looks['01'];document.title=`${d.title} — Maison Noire`;const map={'[data-look-title]':d.title,'[data-look-desc]':d.desc,'[data-look-material]':d.material,'[data-look-colour]':d.colour,'[data-look-construction]':d.construction,'[data-look-origin]':d.origin,'[data-look-edition]':d.edition};Object.entries(map).forEach(([s,v])=>{const el=document.querySelector(s);if(el)el.textContent=v});const im=document.querySelector('[data-look-image]');if(im){im.src=d.img;im.alt=`Maison Noire ${d.title}`};const nx=document.querySelector('[data-look-next]'),pv=document.querySelector('[data-look-prev]');if(nx)nx.href=`look.html?look=${d.next}`;if(pv)pv.href=`look.html?look=${d.prev}`}
const form=document.querySelector('[data-service-form]');if(form)form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const status=form.querySelector('[data-form-status]');try{localStorage.setItem('maison-noire-client-request',JSON.stringify({savedAt:new Date().toISOString(),fields:Object.fromEntries(new FormData(form).entries())}))}catch(_){}if(status){status.hidden=false;status.textContent='Saved on this device for review. No message has been sent from this static site.';status.setAttribute('tabindex','-1');status.focus()}form.classList.add('saved')});
})();