(()=>{
const body=document.body;
const overlay=document.querySelector('[data-menu]');
const openBtn=document.querySelector('[data-menu-open]');
const closeBtn=document.querySelector('[data-menu-close]');
let lastFocus=null;
function openMenu(){if(!overlay)return;lastFocus=document.activeElement;overlay.classList.add('open');body.classList.add('menu-open');overlay.setAttribute('aria-hidden','false');openBtn?.setAttribute('aria-expanded','true');setTimeout(()=>overlay.querySelector('a')?.focus(),20)}
function closeMenu(){if(!overlay)return;overlay.classList.remove('open');body.classList.remove('menu-open');overlay.setAttribute('aria-hidden','true');openBtn?.setAttribute('aria-expanded','false');lastFocus?.focus?.()}
openBtn?.addEventListener('click',openMenu);closeBtn?.addEventListener('click',closeMenu);overlay?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&overlay?.classList.contains('open'))closeMenu();if(e.key==='Tab'&&overlay?.classList.contains('open')){const focusables=[...overlay.querySelectorAll('a,button')].filter(x=>!x.disabled);if(!focusables.length)return;const first=focusables[0],last=focusables.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});

const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const counters=[...document.querySelectorAll('[data-count]')];
if(counters.length){const fill=el=>{const end=Number(el.dataset.count),suffix=el.dataset.suffix||'',prefix=el.dataset.prefix||'';if(reduce){el.textContent=prefix+end+suffix;return}let start=null;const run=t=>{start??=t;const p=Math.min((t-start)/900,1);const value=Math.round(end*(1-Math.pow(1-p,3)));el.textContent=prefix+value+suffix;if(p<1)requestAnimationFrame(run)};requestAnimationFrame(run)};if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){fill(x.target);io.unobserve(x.target)}}),{threshold:.35});counters.forEach(x=>io.observe(x))}else counters.forEach(fill)}

document.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{const value=btn.dataset.filter;const group=btn.closest('[data-filter-group]');group?.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===btn)));document.querySelectorAll('[data-case]').forEach(c=>{c.hidden=value!=='all'&&c.dataset.case!==value})}));

const form=document.querySelector('[data-progressive-form]');
if(form){let step=0;const steps=[...form.querySelectorAll('[data-step]')],progress=[...form.querySelectorAll('[data-progress]')];const render=()=>{steps.forEach((s,i)=>s.classList.toggle('active',i===step));progress.forEach((p,i)=>{p.classList.toggle('active',i===step);p.classList.toggle('done',i<step)});steps[step]?.querySelector('input,select,textarea,button')?.focus({preventScroll:true})};const validate=()=>{const req=[...steps[step].querySelectorAll('[required]')];for(const el of req){if(!el.checkValidity()){el.reportValidity();return false}}return true};form.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>{if(!validate())return;step=Math.min(step+1,steps.length-1);render()}));form.querySelectorAll('[data-prev]').forEach(b=>b.addEventListener('click',()=>{step=Math.max(step-1,0);render()}));form.addEventListener('submit',e=>{e.preventDefault();if(!validate())return;const data=Object.fromEntries(new FormData(form).entries());try{localStorage.setItem('apex-assessment',JSON.stringify({savedAt:new Date().toISOString(),data}))}catch(_){}form.querySelectorAll('[data-step]').forEach(s=>s.classList.remove('active'));const done=form.querySelector('[data-complete]');done.hidden=false;done.tabIndex=-1;done.focus();progress.forEach(p=>p.classList.add('done'));});render()}
})();