(() => {
  const header=document.querySelector('.site-header');const setHeader=()=>header&&header.classList.toggle('is-scrolled',scrollY>12);setHeader();addEventListener('scroll',setHeader,{passive:true});
  const btn=document.querySelector('[data-menu-button]'),nav=document.querySelector('[data-mobile-nav]');const close=()=>{if(!nav||!btn)return;nav.classList.remove('open');btn.setAttribute('aria-expanded','false')};if(btn&&nav)btn.addEventListener('click',()=>{const open=nav.classList.toggle('open');btn.setAttribute('aria-expanded',String(open))});if(nav)nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',close));addEventListener('keydown',e=>e.key==='Escape'&&close());
  document.querySelectorAll('[data-accordion]').forEach(item=>{const q=item.querySelector('button');if(!q)return;q.setAttribute('aria-expanded',item.classList.contains('open')?'true':'false');q.addEventListener('click',()=>{const open=item.classList.toggle('open');q.setAttribute('aria-expanded',String(open))})});
  document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{const group=button.closest('[data-filter-group]');if(!group)return;group.querySelectorAll('[data-filter]').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false')});button.classList.add('active');button.setAttribute('aria-pressed','true');const value=button.dataset.filter;document.querySelectorAll('[data-filter-item]').forEach(item=>item.hidden=value!=='all'&&item.dataset.filterItem!==value)}));
  document.querySelectorAll('form[data-interactive-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const status=form.querySelector('[data-form-status]');if(status){status.textContent=form.dataset.success||'Thanks — your request has been recorded.';status.hidden=false;status.tabIndex=-1;status.focus()}try{const entries=Object.fromEntries(new FormData(form).entries());localStorage.setItem('mosaic-form:'+location.pathname+':'+Date.now(),JSON.stringify({submittedAt:new Date().toISOString(),fields:entries}))}catch(_){}form.classList.add('is-complete')}));
  const slider=document.querySelector('[data-budget-slider]');if(slider){const out=document.querySelector('[data-budget-output]');const sync=()=>{if(out)out.textContent='$'+Number(slider.value).toLocaleString()};slider.addEventListener('input',sync);sync()}
  const css=document.createElement('link');css.rel='stylesheet';css.href='consent.css';document.head.append(css);const key='pennywise-consent-v1';let reopen;
  const footer=document.querySelector('.footer-links');if(footer){const privacy=document.createElement('a');privacy.href='privacy.html';privacy.textContent='Privacy';footer.append(privacy);const terms=document.createElement('a');terms.href='terms.html';terms.textContent='Terms';footer.append(terms);const settings=document.createElement('button');settings.type='button';settings.className='privacy-link';settings.textContent='Cookie settings';settings.addEventListener('click',()=>reopen&&reopen());footer.append(settings)}
  const save=v=>{try{localStorage.setItem(key,v)}catch(_){}document.documentElement.dataset.analytics=v==='analytics'?'on':'off';document.querySelector('[data-penny-consent]')?.remove()};
  const show=()=>{document.querySelector('[data-penny-consent]')?.remove();const el=document.createElement('aside');el.className='penny-consent';el.dataset.pennyConsent='';el.setAttribute('aria-label','Cookie choices');el.innerHTML='<div><strong>Your money is private. Your browsing should be too.</strong><span>We use essential storage for site functions and optional analytics to improve the product experience.</span></div><div class="penny-actions"><button data-choice="essential">Essential only</button><button class="yes" data-choice="analytics">Allow analytics</button></div>';document.body.append(el);el.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>save(b.dataset.choice)))};reopen=show;let choice=null;try{choice=localStorage.getItem(key)}catch(_){}if(choice)document.documentElement.dataset.analytics=choice==='analytics'?'on':'off';else setTimeout(show,500);
})();
