(() => {
  const header=document.querySelector('.site-header');const setHeader=()=>header&&header.classList.toggle('is-scrolled',scrollY>12);setHeader();addEventListener('scroll',setHeader,{passive:true});
  const btn=document.querySelector('[data-menu-button]'),nav=document.querySelector('[data-mobile-nav]');const close=()=>{if(!nav||!btn)return;nav.classList.remove('open');btn.setAttribute('aria-expanded','false')};if(btn&&nav)btn.addEventListener('click',()=>{const open=nav.classList.toggle('open');btn.setAttribute('aria-expanded',String(open))});if(nav)nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',close));addEventListener('keydown',e=>e.key==='Escape'&&close());
  document.querySelectorAll('form[data-interactive-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const status=form.querySelector('[data-form-status]');if(status){status.textContent=form.dataset.success||'Thanks — your request has been recorded.';status.hidden=false;status.tabIndex=-1;status.focus()}try{const entries=Object.fromEntries(new FormData(form).entries());localStorage.setItem('mosaic-form:'+location.pathname+':'+Date.now(),JSON.stringify({submittedAt:new Date().toISOString(),fields:entries}))}catch(_){}form.classList.add('is-complete')}));
  const slider=document.querySelector('[data-budget-slider]');if(slider){const out=document.querySelector('[data-budget-output]');const sync=()=>{if(out)out.textContent='$'+Number(slider.value).toLocaleString()};slider.addEventListener('input',sync);sync()}
  const plan=document.querySelector('[data-plan-select]');if(plan){const requested=new URLSearchParams(location.search).get('plan');if(requested&&[...plan.options].some(o=>o.value===requested))plan.value=requested}

  const css=document.createElement('link');css.rel='stylesheet';css.href='consent.css';document.head.append(css);const key='pennywise-consent-v1';
  const apply=v=>{document.documentElement.dataset.analytics=v==='analytics'?'on':'off'};const store=v=>{try{localStorage.setItem(key,v)}catch(_){}apply(v)};
  const report=v=>{const status=document.querySelector('[data-consent-status]');if(status){status.textContent=v==='analytics'?'Anonymous analytics are allowed in this browser.':'Only essential storage is enabled in this browser.';status.hidden=false}};
  const save=v=>{store(v);document.querySelector('[data-penny-consent]')?.remove();report(v)};
  const show=()=>{document.querySelector('[data-penny-consent]')?.remove();const el=document.createElement('aside');el.className='penny-consent';el.dataset.pennyConsent='';el.setAttribute('aria-label','Cookie choices');el.innerHTML='<div><strong>Your money is private. Your browsing should be too.</strong><span>We use essential storage for site functions and optional analytics to improve the product experience.</span></div><div class="penny-actions"><button data-choice="essential">Essential only</button><button class="yes" data-choice="analytics">Allow analytics</button><a href="privacy.html#cookie-settings">Review settings</a></div>';document.body.append(el);el.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>save(b.dataset.choice)))};
  document.querySelectorAll('[data-consent-choice]').forEach(b=>b.addEventListener('click',()=>save(b.dataset.consentChoice)));
  let choice=null;try{choice=localStorage.getItem(key)}catch(_){}if(choice){apply(choice);report(choice)}else setTimeout(show,500);
})();
